name: grid
description: Common classes to convert between square grids and hexagonal grids.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
