name: grid_space
description: Common classes to convert between square grids and hexagonal grids.
version: 1.0.0
repository: https://github.com/doodlezucc/dart_grid_space

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
